# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classic',
            fields=[
                ('move_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Move')),
            ],
            options={
                'ordering': ('-name',),
            },
            bases=('main.move',),
        ),
    ]
